name: container
on: push 

jobs:
    node-docker:
        runs-on: ubuntu-latest
        container:
            image: node:20-alpine3.17
        steps:
            - name: log node version
              run: |
                node -v 
                cat /etc/os-release
