name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  functions_expressions:
    runs-on: ubuntu-latest
    steps:
        - name: expressions
          run: |
            echo ${{ contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
            echo ${{ startsWith('Hello world', 'He') }}
            echo ${{ endsWith('Hello world', 'ld') }}

  func_status_checks:
    runs-on: ubuntu-latest
    steps:
        - name: step1
          run: echooo "hello"
          
        - name: step2
        #   if: failure()
          run: echo "I need this step to execute even if previous step fails"
          
        - name: step3
          if: always()
          run: echo "this step will always run, success or failed step"
          


