name: depsjod
on:
    workflow_run:
        workflows: [simple]
        types: [completed]
jobs:
    simple_deps_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: run after main job completed
              run: echo "I was run after my boss job(simple) completed."

    