name: shell cmds workflow
run-name: shell cmds workflow
on: 
  push:
    branches: 
      - master
  # pull_request: 
  #   types: [closed,reopened,opened]

jobs:
  run-shell-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello world"

      - name: multiline script
        run: |
          node -v
          npm -v 

      - name: python command 
        run: | 
          import platform
          print(platform.processor())
        shell: python
  run-windows-cmds:
    runs-on: windows-latest
    needs: 
      - run-shell-cmds
    steps:
      - name: Directory
        run: Get-location

      - name: Directory bash
        run: pwd
        shell: bash
  

