name: ghactions tutorial
run-name: example demo
on: push
jobs:
  run-shell-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v 
      - name: python command 
        run: | 
          import platform
          print(platform.processor())
        shell: python

