name: custom vars
on:
    push
env:
    WF_ENV: "env for workflow"

jobs:
    create_issue:
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
          - name: push a random file
            run: |
                git init 
                git remote add origin "https://samperay:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git config --global user.email "mybot@gmail.com"
                git config --global user.name "mybot"
                git fetch
                git checkout master
                git branch --set-upstream-to=origin/master
                git pull 
                ls -la
                echo $RANDOM >> random.txt
                ls -la
                git add -A
                git commit -m "added random file"
                git push 

          - name: Create issue using REST API
            run: |
              curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/issues \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '{
                "title": "Automated issue for commit: ${{ github.sha }}",
                "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                }' \
              --fail
    
    log-env:
        runs-on: ubuntu-latest
        env: 
            JOB_ENV: env for job
        steps:
            - name: display all envs
              env:
                STEP_ENV: env for step
              run: |
                echo "WF_ENV: ${WF_ENV}"
                echo "JOB_ENV: ${JOB_ENV}"
                echo "STEP_ENV: ${STEP_ENV}"

            - name: display workflow and job env
              run: |
                echo "WF_ENV: ${WF_ENV}"
                echo "JOB_ENV: ${JOB_ENV}"
                echo "STEP_ENV: ${STEP_ENV}"
    log-default-env:
        runs-on: ubuntu-latest
        steps:
            - name: display all default envs
              run: |
                echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
                echo "GITHUB_JOB: ${GITHUB_JOB}"
                echo "RUNNER_ARCH: ${RUNNER_ARCH}"
                echo "RUNNER_OS: ${RUNNER_OS}"
                echo "WF_ENV: ${WF_ENV}"
                echo "JOB_ENV: ${JOB_ENV}"
                echo "STEP_ENV: ${STEP_ENV}"

